# Конфигурация пайплайна МО для диагностики рака молочной железы
data:
  source_file: "wdbc.data"
  target_column: "diagnosis"
  id_column: "id"
  feature_columns:
    - "radius_mean"
    - "texture_mean" 
    - "perimeter_mean"
    - "area_mean"
    - "smoothness_mean"
    - "compactness_mean"
    - "concavity_mean"
    - "concave_points_mean"
    - "symmetry_mean"
    - "fractal_dimension_mean"
    - "radius_se"
    - "texture_se"
    - "perimeter_se"
    - "area_se"
    - "smoothness_se"
    - "compactness_se"
    - "concavity_se"
    - "concave_points_se"
    - "symmetry_se"
    - "fractal_dimension_se"
    - "radius_worst"
    - "texture_worst"
    - "perimeter_worst"
    - "area_worst"
    - "smoothness_worst"
    - "compactness_worst"
    - "concavity_worst"
    - "concave_points_worst"
    - "symmetry_worst"
    - "fractal_dimension_worst"

model:
  type: "logistic_regression"
  test_size: 0.2
  random_state: 42
  solver: "liblinear"
  max_iter: 1000

storage:
  type: "local"  # Варианты: local, gcs, dropbox, s3
  results_path: "results/"
  model_filename: "breast_cancer_model.joblib"
  metrics_filename: "model_metrics.json"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
validation:
  required_columns: 32  # ID + диагноз + 30 признаков
  min_samples: 100
